MODEL:
  PRETRAIN_CHOICE: 'self'
  PRETRAIN_PATH: './checkpoints/stage1/transreid_256/transformer_40.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: 0
  Transformer_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [14, 14]

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('veri')
  DATA_ROOT: '../AIC21/veri_pose'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 8
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 3
  BASE_LR: 0.0004
  IMS_PER_BATCH: 96
  STEPS: [40, 70]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: True
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 3
  LOG_PERIOD: 50
  EVAL_PERIOD: 10000
  FP16_ENABLED: True

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: True
  RE_RANKING_TRACK: True
  WEIGHT: './checkpoints/stage2/transreid_256/v1/transformer_2.pth'
  ENCODERS:
    E: "./gan/weights/GAN_stage_2/17_net_E.pth"
    G: "./gan/weights/GAN_stage_2/17_net_G.pth"
    Di: "./gan/weights/GAN_stage_2/17_net_Di.pth"
    Dp: "./gan/weights/GAN_stage_2/17_net_Dp.pth"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  FLIP_FEATS: 'no'
  EVAL: True
  FIC: True
  CROP_TEST: True
  LA: 0.11

STAGE2:
  EPS: 0.55
  LA: 0.0005
      
OUTPUT_DIR: './logs/stage2/transreid_256/veri'
